version: "3"
services:
  portfoio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=hemant
      - CHINESE_FOOD= rtuoh
      - WATCHPACK_POLLING=TRUE

